### ISSUE TITLE
ImportError: cannot import name AppIndicator3, introspection typelib not found

### ISSUE THREAD

**Issue by DoodleCup** [centic9/headset-charge-indicator#1]
$ python3 headset-charge-indicator.py /home/bugs/HeadsetControl/build
headset-charge-indicator.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib
Traceback (most recent call last):
  File "headset-charge-indicator.py", line 13, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 133, in load_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name AppIndicator3, introspection typelib not found

**Comment by centic9** [comment]
Some python module/component is missing, did you install the required modules as listed in the README?

**Comment by DoodleCup** [comment]
yes

**Comment by centic9** [comment]
I fixed a few of the warnings, they are unrelated, please check "ImportError: cannot import name AppIndicator3, introspection typelib not found"

Please take a look at Google search-results for this, there are many discussions about missing packages which could cause this.

If that does not help please specify in more detail your environment, operation system, version of python, ...

**Comment by centic9** [comment]
Also try installing gir1.2-appindicator3-0.1

**Comment by centic9** [comment]
I added gir1.2-appindicator3-0.1 to the list of required packages, installing this one should hopefully fix your problem.

**Comment by DoodleCup** [comment]
Sorry for the late reply. Was busy.

I installed the gir1.2-appindicator3-0.1 package.

Now i get this errors:
`user@Debian:~/HeadsetControl/build$ sudo python3 headset-charge-indicator.py /home/user/HeadsetControl/build

headset-charge-indicator.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib

headset-charge-indicator.py:13: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.

  from gi.repository import AppIndicator3 as appindicator
Traceback (most recent call last):

  File "headset-charge-indicator.py", line 57, in <module>
    change_label(None)

  File "headset-charge-indicator.py", line 25, in change_label
    output=check_output([HEADSETCONTROL_BINARY,"-b","-c"] )

  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout

  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:

  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

PermissionError: [Errno 13] No permission: '/home/user/HeadsetControl/build'
`
(Used Sudo to launch. But without sudo the same errors appear)

**Comment by centic9** [comment]
I expect that /home/user/HeadsetControl/build does not actually exist for you.

Thne it looks like you did not actually clone and build the additional HeadsetControl binary, please take a look at the instructions in the README again.

**Comment by centic9** [comment]
You might also specify a directory whereas the application requires the path to the executable file, i.e. try /home/user/HeadsetControl/build/headsetcontrol if you actually downloaded and built the binary under  /home/user/HeadsetControl/
