### ISSUE TITLE
logitech g733

### ISSUE THREAD

**Issue by ctrlBIRDdelete** [centic9/headset-charge-indicator#10]
$ sudo python3 headset-charge-indicator.py --headsetcontrol-binary /home/alex/HeadsetControl/build/headsetcontrol
Error: This headset doesn't support chat-mix level
Command '['/home/alex/HeadsetControl/build/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
Error: This headset doesn't support chat-mix level
Command '['/home/alex/HeadsetControl/build/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
Error: This headset doesn't support chat-mix level
Command '['/home/alex/HeadsetControl/build/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
Error: This headset doesn't support chat-mix level
Command '['/home/alex/HeadsetControl/build/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
Error: This headset doesn't support chat-mix level
Command '['/home/alex/HeadsetControl/build/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
^CTraceback (most recent call last):
  File "headset-charge-indicator.py", line 382, in <module>
    Gtk.main()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1649, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

I'm able to use headsetcontrol on it's own but can't figure out how to make icon appear because of this issue.

Fresh Ubuntu 20.10

**Comment by centic9** [comment]
The error about chat-mix should be handled gracefully and should not affect displaying icons or other functionality. 

You can try to comment out the call to the chatmix-function at https://github.com/centic9/headset-charge-indicator/blob/master/headset-charge-indicator.py#L290 and see if that makes the icon appear for you.

The support for app-indicators varies a lot between desktop environments, see the information at https://github.com/centic9/headset-charge-indicator/blob/master/README.md#supported-desktop-envrionemnts

If you can provide details about the type and version of desktop environment that you are using and the versions of the related packages, I can try to take a look, but it seems support is very much depending on the actual desktop environment... :(

**Comment by centic9** [comment]
The latest version from master-branch makes use of new headset-control features to detect capabilities and thus should not try to read chat-mix level. 

Closing for now as I don't see anything that I can fix in the code here.

Please reopen if you find some way to make it work or if the desktop environment that you are using is reported to work in the README. Please include version-information of all related packages if possible.
