### ISSUE TITLE
Corsair Void Elite Wless "This headset doesn't support chat-mix level"

### ISSUE THREAD

**Issue by Whachi** [centic9/headset-charge-indicator#11]
Im trying to get the indicator running, but on startup i keep getting this error, 

`sudo python3 headset-charge-indicator.py --headsetcontrol-binary /usr/local/bin/headsetcontrol
Error: This headset doesn't support chat-mix level
Command '['/usr/local/bin/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
Error: This headset doesn't support chat-mix level
Command '['/usr/local/bin/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
Error: This headset doesn't support chat-mix level
Command '['/usr/local/bin/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
`

Things already tried
* comment out the call to the chatmix-function at https://github.com/centic9/headset-charge-indicator/blob/master/headset-charge-indicator.py#L290 and no error anymore but the application does not actually start - just a blank line in terminal
* Install package gnome-shell-extension-appindicator.
Restarted gnome
ran gnome-shell-extension-prefs and "KStatusNotifierItem/AppIndicator" was not there

I am very new to Linux and do not know what to do to fix my issue.
Headset control works with no issues.

using Ubuntu 20.10 - Gnome

**Comment by centic9** [comment]
If you are running the latest version from master-branch, the error-message about chat-mix should not keep the tool from working fine. The output indicates that it was running and just printing that out periodically whenever it tried to refresh the information.

Please note that the app-indicator functionality seems to be not fully supported on some desktop environments, see the description in the readme at https://github.com/centic9/headset-charge-indicator#supported-desktop-envrionemnts for a list of how well it works on which desktop environment.

**Comment by centic9** [comment]
Closing for now as I don't see anything that I can fix in the code here. 

Please reopen if you find some way to make it work or if the desktop environment that you are using is reported to work in the README. Please include version-information of all related packages if possible.
