### ISSUE TITLE
Doesn't Work on Pop! Os 20.04 with Void Pro Wireless

### ISSUE THREAD

**Issue by Lunarnovaa** [centic9/headset-charge-indicator#13]
https://i.imgur.com/zVsrSle.png

Nothing pops up in the top right of my screen. Is there a way to fix this? I've tried everything I can think of, and yes I do have the gnome tweak for app indicators.

**Comment by centic9** [comment]
You are not providing the necessary commandline options. Please take a look at the last line of output and take a look at the documentation in the README.md.
