### ISSUE TITLE
systemctl service or another way of starting this automatically and running in background

### ISSUE THREAD

**Issue by scr4bble** [centic9/headset-charge-indicator#14]
Hello,

what about building a service file for systemd for starting this on system startup and running in the background?
Or is there any other (better) way how to achieve this?
Any plan of adding this into gnome shell extensions so people can just "enable it" in the shell extensions UI?

I am willing to help/contribute if needed.

**Comment by centic9** [comment]
I currently run this from the commandline so no immediate plans myself to work on systemd integration, but I am open to adding a sample service-file and other material for automating the setup. 

Similar to Gnome Shell, I am not using it currently, so I will likely not spend too much time on it, but will try to incorporate changes/PRs (as long as they still support the current way of running it manually).

**Comment by scr4bble** [comment]
Tried the systemd way but unsuccessfully. After reading some SO posts I realized that systemd is not a good way for starting an app interacting with user session.
Will post another way how to automate the app start.

**Comment by scr4bble** [comment]
Created a pull requests. Please review and make the file executable if possible.
https://github.com/centic9/headset-charge-indicator/pull/15

**Comment by centic9** [comment]
Fixed via #15, thanks for the PR!
