### ISSUE TITLE
ValueError: Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by KuntaoDaChump** [centic9/headset-charge-indicator#17]
For some reason the app didnt start on login, after trying to start it manually, nothing is happening. After attempting to run it in a terminal, I get this error;

python3 headset-charge-indicator.py
Traceback (most recent call last):
  File "/home/ranger/ManualInstalls/HeadsetChargeIndicator/headset-charge-indicator.py", line 21, in <module>
    require_version('AyatanaAppIndicator3', '0.1')
  File "/usr/lib64/python3.12/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ranger/ManualInstalls/HeadsetChargeIndicator/headset-charge-indicator.py", line 25, in <module>
    require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python3.12/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

I don't believe I started it wrong as I've done it before like this. Am I missing something? AyatanaAppIndicator3 doesn't exist so I could install it. HeadsetControl is still working as expected.

I see in the post that it says something about Ayatana, but it refers to Debian and I am on Fedora 39. Any help would be greatly appreciated.

**Comment by centic9** [comment]
You are missing required libraries for app-indicators, not sure what package this is for Fedora or if it is even available, probably something like `appindicator`, `libappindicator`,  `ayatanaappindicator` or similar.

I don't run Fedora, so can't tell what exactly you might need.

See also https://github.com/centic9/headset-charge-indicator?tab=readme-ov-file#installation for related instructions.

Please let me know if you find out so we can update the instructions in the README.

**Comment by KuntaoDaChump** [comment]
I have libappindicator-12.10.1-2.fc39.x86_64 already installed and seems to be the latest version.

**Comment by centic9** [comment]
On Debian there is the additional package `gir1.2-ayatanaappindicator3-0.1` which is required as well. 

Do you have a similar one available in Fedora? 
Or anything else with "appindicator" or "ayatana" in the name?

**Comment by KuntaoDaChump** [comment]
I'll look around for it but Im not sure why this would be happening out of the blue. I've been using this with no issues for about 2 weeks now.

**Comment by KuntaoDaChump** [comment]
I finally had some time to work on it. I ran the following commands and it seems to have started. I'll let you know if I have any further issues!

sudo dnf install libindicator

& 

sudo dnf install libayatana-appindicator-gtk3

Btw Im using Fedora 39.

**Comment by centic9** [comment]
Thanks, I have updated the README accordingly
