### ISSUE TITLE
SteelSeries Arctis (7/Pro) + Debian 10: no battery percentage

### ISSUE THREAD

**Issue by SebStaeubert** [centic9/headset-charge-indicator#7]
Hi,

i see the headset-icon and can open the menu. But there is no battery percentage next to the small headset icon.

How to fix this?

Output of './headset-charge-indicator.py --headsetcontrol-binary /usr/local/bin/headsetcontrol --verbose'
`Bat: 89
ChatMix: 64`

Kind regards,
Sebastian

**Comment by centic9** [comment]
Which window manager is this? 

I saw a similar behavior when I tested a few different ones some time ago, see https://github.com/centic9/headset-charge-indicator#supported-desktop-envrionemnts for my results. 

It seems some window managers do not allow to add such text to the icon, at least I did not see any way to affect how the appindicator functionality could be used differently to make it work on those system.

So I am afraid I don't know how to make this better, if you can find a way with python and app-indicator to display such a text, I can try to adjust the tool, naturally.

**Comment by SebStaeubert** [comment]
Its gnome 3.30.2 (Debian 10, 64Bit).

Have you any insight/hints how to fix this in gnome resp. how did you manage to display the battery percentage text next to the icon in gnome? Or was this not included when you ran the test which results in "GNOME: Works fully"?

Unfortunately i don't have any experience nether in python nor in developing gnome interactions.

**Comment by centic9** [comment]
It seems even different versions of gnome behave differently, I mostly tested the current Ubuntu/Debian versions, but did not record which version exactly.

I have now created a small test-application which allows to test if your desktop environment supports app-indicator properly:

Please fetch the latest version of this project and then invoke the test-application as follows:

`python3 test-app-indicator.py`

This tries to create a very simple app-indicator with a "stop" sign as icon, the text "-1 %" and a menu-item to quick the indicator.

For me it looks this way: 
![image](https://user-images.githubusercontent.com/548322/105989218-1861dd00-60a1-11eb-90c5-e8460ec3fd38.png)

**Comment by mawiegand** [comment]
KDE also does not display any label.
What about using Qt instead of GTK3?

**Comment by admorgan** [comment]
I have the same problem with Gnome 3.38 using the Topicons Plus extension on SUSE Tumbleweed.

**Comment by admorgan** [comment]
I changed the notification panel to Appindicator and kstatusnotifieritem support from Ubuntu and now the charge works correctly.

**Comment by SebStaeubert** [comment]
@centic9 
> `python3 test-app-indicator.py`

Looks like this:
![headset-charge-indicator](https://user-images.githubusercontent.com/11329281/106575565-83496300-653c-11eb-9e70-e49d1a4fb7c9.png)

And there is this message in the console:
`(test-app-indicator.py:29304): Gdk-CRITICAL **: 09:51:21.548: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

@admorgan 
> I changed the notification panel to Appindicator and kstatusnotifieritem support from Ubuntu and now the charge works correctly.

How did you change this?

**Comment by admorgan** [comment]
If you have the Gnome Shell Extension installed in your browser (For chrome https://chrome.google.com/webstore/detail/gnome-shell-integration) you can go to https://extensions.gnome.org/extension/615/appindicator-support and click the on/off button to install it. Then in the Gnome Tweaks application on your system go to the Extensions tab and enable it. You can only have one notification panel at a time, so you will need to disable any others that are enabled.

**Comment by SebStaeubert** [comment]
@admorgan Now i have the percentage. THX!

@centic9 I leave it to you to close the ticket. admorgans solution works but utilizes KDE stuff to make it work for gnome user. This ist ok for me, but if you plan a nice solution, you can still leave the ticket open ;-)

Thx for the indicator tool and the solution!

**Comment by centic9** [comment]
Thanks for the research and finding out about this requirement/workaround.

I have now updated the README to state that this extension might be necessary to make it work. 

I don't see any other way to influence the display of the indicator from the application side, thus I am closing this for now.
